### PR TITLE
#92 Fix pom.xml: slf4j & logback dependencies

### PR DESCRIPTION
**Pull request by MaximDribas**
#92 Fix pom.xml: slf4j & logback dependencies

### CODE REVIEW

**Comment by Benkoff** [comment]
Nice job! I like classic style 🥇

**Comment by danilkuznetsov** [comment]
I think It's not good idea to  manual  include  dependencies  for logging system  instead using spring dependencies management.
Spring has powerfull system for management all versions for dependencies 
Also new version spring boot has some new changes

spring-boot-mvc-parent includes spring-boot-logging-parent by default

spring boot logging parent manages dependencies for logging 

we will try to remove  spring-boot-logging-parent but we aren't adding new dependecies 


we should remove all this lines

        
            
            
            
        
        
            
            
            
        
        
            
            
            
        

See more https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-starters/spring-boot-starter-logging/pom.xml

See more https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html

**Comment by danilkuznetsov** [comment]
If this doesn't work for you, I will try to help you

**Comment by Benkoff** [comment]
@danilkuznetsov 
i've added these dependecies:
+        <dependency>
+            <groupId>org.slf4j</groupId>
+            <artifactId>slf4j-api</artifactId>
+            <version>1.7.25</version>
+        </dependency>
+        <dependency>
+            <groupId>org.slf4j</groupId>
+            <artifactId>slf4j-simple</artifactId>
+            <version>1.7.25</version>
+        </dependency>
because Spring had 'SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".' error as described in  issue #71 , solution taken from: https://stackoverflow.com/questions/7421612/slf4j-failed-to-load-class-org-slf4j-impl-staticloggerbinder

**Comment by Benkoff** [comment]
i've tried
```
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.8</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.1.8</version>
        </dependency>
```
and it works for me

**Pull request merged**
